---
galaxy_info:
  author: HyperSec
  description: DFE developer environment component
  company: HyperSec
  license: Apache-2.0
  min_ansible_version: "2.20"
  platforms:
    - name: Fedora
      versions: ['42']
    - name: Ubuntu
      versions: ['noble']

dependencies: []
