---
- name: Test Git Installation on macOS
  hosts: all
  become: false
  gather_facts: true

  tasks:
    - name: Include git tasks
      ansible.builtin.include_tasks:
        file: roles/dfe_developer/tasks/git.yml
